"""The common part of message decoder/encoder.

Contains the identifiers of messages.

"""

HEARTBEAT_ANNOUNCEMENT                  =  1
LOAD_GRAPH_AND_WORK_REQUEST             =  2
LOAD_GRAPH_AND_WORK_RESPONSE            =  3
LOAD_WORK_DETAILS_REQUEST               =  4
LOAD_WORK_DETAILS_RESPONSE              =  5
POKE_ANNOUNCEMENT                       =  6
PRESENT_YOURSELF_REQUEST                =  7
PRESENT_YOURSELF_RESPONSE               =  8
CANT_EXECUTE_WORK_NOW_ANNOUNCEMENT      =  9
COMMAND_REQ_EXECUTE_GRAPH               = 10
COMMAND_RES_EXECUTE_GRAPH               = 11
COMMAND_REQ_ELECTION                    = 12
COMMAND_RES_ELECTION                    = 13
COMMAND_REQ_DETERMINE_GRAPH_CYCLE       = 14
COMMAND_RES_DETERMINE_GRAPH_CYCLE       = 15
COMMAND_REQ_ORDER_WORK_EXECUTION        = 16
COMMAND_RES_ORDER_WORK_EXECUTION        = 17
COMMAND_REQ_EXECUTE_WORK                = 18
COMMAND_RES_EXECUTE_WORK                = 19
COMMAND_REQ_DETERMINE_WORK_CYCLE        = 20
COMMAND_RES_DETERMINE_WORK_CYCLE        = 21
