"""The common part of message decoder/encoder.

Contains the identifiers of messages.

"""

COMMAND_WORK_EXECUTION_ANNOUNCEMENT     =  1
DETERMINE_GRAPH_CYCLE_REQUEST           =  2
DETERMINE_GRAPH_CYCLE_RESPONSE          =  3
DETERMINE_WORK_CYCLE_REQUEST            =  4
DETERMINE_WORK_CYCLE_RESPONSE           =  5
EXECUTE_GRAPH_ANNOUNCEMENT              =  6
EXECUTE_WORK_ANNOUNCEMENT               =  7
HEARTBEAT_ANNOUNCEMENT                  =  8
LOAD_GRAPH_AND_WORK_REQUEST             =  9
LOAD_GRAPH_AND_WORK_RESPONSE            = 10
LOAD_WORK_DETAILS_REQUEST               = 11
LOAD_WORK_DETAILS_RESPONSE              = 12
POKE_ANNOUNCEMENT                       = 13
PRESENT_YOURSELF_REQUEST                = 14
PRESENT_YOURSELF_RESPONSE               = 15
REPORT_FINISHED_WORK_ANNOUNCEMENT       = 16
CANT_EXECUTE_WORK_NOW_ANNOUNCEMENT      = 17
EXECUTE_GRAPH_SEEK_VOLUNTEERS           = 18
EXECUTE_GRAPH_VOLUNTEE                  = 19
EXECUTE_GRAPH_SELECT_VOLUNTEER          = 20
COMMAND_WORK_EXECUTION_SEEK_VOLUNTEERS  = 21
COMMAND_WORK_EXECUTION_VOLUNTEE         = 22
COMMAND_WORK_EXECUTION_SELECT_VOLUNTEER = 23
COMMAND_REQ_EXECUTE_GRAPH               = 24
COMMAND_RES_EXECUTE_GRAPH               = 25
COMMAND_REQ_ELECTION                    = 26
COMMAND_RES_ELECTION                    = 27
COMMAND_REQ_DETERMINE_GRAPH_CYCLE       = 28
COMMAND_RES_DETERMINE_GRAPH_CYCLE       = 29
COMMAND_REQ_ORDER_WORK_EXECUTION        = 30
COMMAND_RES_ORDER_WORK_EXECUTION        = 31
