"""The common part of message decoder/encoder.

Contains the identifiers of messages.

"""

COMMAND_WORK_EXECUTION_ANNOUNCEMENT =  1
DETERMINE_GRAPH_CYCLE_REQUEST       =  2
DETERMINE_GRAPH_CYCLE_RESPONSE      =  3
EXECUTE_GRAPH_ANNOUNCEMENT          =  4
EXECUTE_WORK_ANNOUNCEMENT           =  5
HEARTBEAT_ANNOUNCEMENT              =  6
LOAD_GRAPH_AND_WORK_REQUEST         =  7
LOAD_GRAPH_AND_WORK_RESPONSE        =  8
POKE_ANNOUNCEMENT                   =  9
PRESENT_YOURSELF_REQUEST            = 10
PRESENT_YOURSELF_RESPONSE           = 11
